MVC_Project/sortNumbers/Models/NumbersLine.cs
using System;
using System.ComponentModel.DataAnnotations;


namespace sortNumbers.Models
{
    public class NumbersLine
    {
        public int[] numbers{get; set;}

        [Required (ErrorMessage = "This field cannot be empty!")]
        [RegularExpression(@"([0-9]+,)*[0-9]+", ErrorMessage = "Invalid input! (ex: 2,3,1)")]
        public string numberstext{get; set;}
        public long bubbleSortTime{get;set;}
        public long quickSortTime{get;set;}
        public long mergeSortTime{get;set;}

        public void arrayFromString(){
            try
            {
                if(numberstext!=null)
                {
                    numbers = Array.ConvertAll(numberstext.Replace(" ", "").Split(","), Int32.Parse);
                }
                
                numberstext = null;
            }
            catch(Exception)
            {
                numbers = null; 
            }
            
        }

        public void mergeSort(){
            var watch = new System.Diagnostics.Stopwatch();

            watch.Start();
            numbers = mergeSort(numbers);
            watch.Stop();

            mergeSortTime = watch.ElapsedMilliseconds;
        }

        private static int[] mergeSort(int[] array)
        {
            int[] left, right, result;  
            
            if (array.Length <= 1)
            {
                return array;              
            }

            int midPoint = array.Length / 2;  
            
            left = new int[midPoint];
  
            if (array.Length % 2 == 0)
            {
                right = new int[midPoint];  
            }
            else
            {
                right = new int[midPoint + 1]; 
            } 
            
            for (int i = 0; i < midPoint; i++)
            {
                left[i] = array[i];  
            }
            
            int x = 0;
            
            for (int i = midPoint; i < array.Length; i++)
            {
                right[x] = array[i];
                x++;
            }  
            
            left = mergeSort(left);
            right = mergeSort(right);     
            result = merge(left, right);  
            
            return result;
        }
  
        private static int[] merge(int[] left, int[] right)
        {
            int resultLength = right.Length + left.Length;
            int[] result = new int[resultLength];
            
            int indexLeft = 0, indexRight = 0, indexResult = 0;  
            
            while (indexLeft < left.Length || indexRight < right.Length)
            {
                if (indexLeft < left.Length && indexRight < right.Length)  
                {  
                    if (left[indexLeft] <= right[indexRight])
                    {
                        result[indexResult] = left[indexLeft];
                        indexLeft++;
                        indexResult++;
                    }
                    
                    else
                    {
                        result[indexResult] = right[indexRight];
                        indexRight++;
                        indexResult++;
                    }
                }
                
                else if (indexLeft < left.Length)
                {
                    result[indexResult] = left[indexLeft];
                    indexLeft++;
                    indexResult++;
                }
                
                else if (indexRight < right.Length)
                {
                    result[indexResult] = right[indexRight];
                    indexRight++;
                    indexResult++;
                }  
            }
            return result;
        }

        public void bubbleSort(){
            var watch = new System.Diagnostics.Stopwatch();
            int n;

            watch.Start();
            for (n = numbers.Length; n>= 2; n--)
            {
                for (int j = 0; j <= n - 2; j++)
                {
                    if (numbers[j] > numbers[j + 1])
                    {
                        int tmp = numbers[j + 1];
                        numbers[j + 1] = numbers[j];
                        numbers[j] = tmp;
                    }
                } 
            }
            watch.Stop();

            bubbleSortTime = watch.ElapsedMilliseconds;
        }

        public void quickSort(){
            var watch = System.Diagnostics.Stopwatch.StartNew();

            Quick_Sort(numbers, 0, numbers.Length-1);
            watch.Stop();

            quickSortTime = watch.ElapsedMilliseconds;
        }

        private static void Quick_Sort(int[] arr, int left, int right) 
        {
            if (left < right)
            {
                int pivot = Partition(arr, left, right);

                if (pivot > 1) {
                    Quick_Sort(arr, left, pivot - 1);
                }
                if (pivot + 1 < right) {
                    Quick_Sort(arr, pivot + 1, right);
                }
            }
        
        }

        private static int Partition(int[] arr, int left, int right)
        {
            int pivot = arr[left];
            while (true) 
            {

                while (arr[left] < pivot) 
                {
                    left++;
                }

                while (arr[right] > pivot)
                {
                    right--;
                }

                if (left < right)
                {
                    if (arr[left] == arr[right]) return right;

                    int temp = arr[left];
                    arr[left] = arr[right];
                    arr[right] = temp;
                }
                else 
                {
                    return right;
                }
            }
        }
    }
    
}

MVC_Project/sortNumbers/Controllers/NumbersLineController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using sortNumbers.Models;
using sortNumbers.Data;
using sortNumbers.Dtos;
using AutoMapper;

namespace sortNumbers.Controllers
{
    public class NumbersLineController : Controller
    {
        private readonly INumbersLineRepository _repository;
        private readonly IMapper _mapper;

        public NumbersLineController(INumbersLineRepository repository, IMapper mapper)
        {
            _repository = repository;
            _mapper = mapper;
        }

        [HttpGet]
        public ActionResult <NumbersLine> Index()
        {      
            return View();
        }

        [HttpGet]
        public ActionResult <NumbersLineReadDto> Get()
        {
            NumbersLine numbersLine = _repository.GetNumbersLine();
            NumbersLineReadDto numbersLineReadDto = _mapper.Map<NumbersLineReadDto>(numbersLine);
            return View(numbersLineReadDto);
        }

        public ActionResult <NumbersLinePostDto> Post()
        {
            return View();
        }

        public ActionResult <NumbersLine> Help()
        {
            return View();
        }

        [HttpPost]
        public ActionResult <NumbersLinePostDto> Post(NumbersLinePostDto numbersLinePostDto)
        {
            NumbersLine numbersLine = _mapper.Map<NumbersLine>(numbersLinePostDto);
            NumbersLine response = null;

            if (ModelState.IsValid && numbersLine.numberstext!=null)
            {
                numbersLine.arrayFromString();
                if(numbersLine.numbers!=null)
                {
                    NumbersLine bubbleArray = numbersLine;
                    NumbersLine quickArray = numbersLine;
                    NumbersLine mergeArray = numbersLine;

                    bubbleArray.bubbleSort();
                    quickArray.quickSort();
                    mergeArray.mergeSort();

                    if(!bubbleArray.numbers.Equals(quickArray.numbers) || 
                       !bubbleArray.numbers.Equals(mergeArray.numbers))
                    {
                        throw new Exception("Arrays are different!");
                    }

                    response = mergeArray;
                    response.quickSortTime = quickArray.quickSortTime;
                    response.bubbleSortTime = bubbleArray.bubbleSortTime;
                    _repository.PostNumbers(response);
                }
            }

            return View(response);
        }
    }
}

MVC_Project/sortNumbers/Views/NumbersLine/Get.cshtml
@model sortNumbers.Dtos.NumbersLineReadDto
<form method="get" asp-action="Get">   
    <div class="border p-3">
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
        <div class="form-group row" style="border-top-width: 2%; border-top-style: solid; border-top-color: #eaecef; margin-top: 2.5%; padding-top: 2.5%;">
            <h2 class="text-info pl-3">LAST SAVED FILE SORT RESULT</h2>
        </div>

        @{int count=0;}
        @if(Model!=null && Model.numbers!=null){    
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            Index
                        </th>
                        <th>
                            Number
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.numbers) {
                        <tr>
                            <td>
                                @count
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item)
                            </td>
                        </tr>
                        {count++;}
                    }
                </tbody>
            </table>
        }else{
            <p>
                No sort of numbers to show.
            </p>
        }
    </div>
</form>

MVC_Project/sortNumbers/Views/NumbersLine/Index.cshtml
<div class="border p-3">
    <div class="form-group row">
        <h2 class="text-info pl-3">Assignment - Sort of a line of numbers</h2>
    </div>
    <div class="form-group row" style="border-top-width: 2%; border-top-style: solid; border-top-color: #eaecef; margin-top: 2.5%; padding-top: 2.5%;">
        <span style="margin: 2%;">
            <p>This is a MVC version of the assignment.</p>
            <p>In the tab area "Sort Numbers" is possible to insert numbers to sort.</p>
            <p>Is also possible to check the execution time of each sort algorithm in milliseconds.</p>
            <p>All the times a new sort is done, one new file is created with the sort result. The files are in the folder "files".</p>
            <p>In the tab area "View Numbers" is possible to view the sort result of last saved file.</p>
        </span>
    </div>
</div>

MVC_Project/sortNumbers/Views/NumbersLine/Post.cshtml
@model sortNumbers.Models.NumbersLine

<form method="post">
    <div class="border p-3">
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
        <div class="form-group row">
            <h2 class="text-info pl-3">SORT NUMBERS</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4" style="text-align: right;">
                        <label asp-for="numberstext" style="font-weight: bold;">Insert numbers:</label>
                    </div>
                    <div class="col-8">
                        <input asp-for="numberstext" placeholder="ex: 2,4,6" class="form-control" value=""/> 
                        <span asp-validation-for="numberstext" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-4" style="text-align: right; font-weight: bold;">
                        <label asp-for="quickSortTime">Quick Sort Time:</label>
                    </div>
                    <div class="col-1">
                        <label>@Html.DisplayFor(numbersLine => numbersLine.quickSortTime)</label>
                    </div>
                    <div class="col-4">
                        <label>milliseconds</label>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-4" style="text-align: right; font-weight: bold;">
                        <label asp-for="bubbleSortTime" style="text-align: right;">Bubble Sort Time:</label>
                    </div>
                    <div class="col-1">
                        <label>@Html.DisplayFor(numbersLine => numbersLine.bubbleSortTime)</label>
                    </div>
                    <div class="col-4">
                        <label>milliseconds</label>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-4" style="text-align: right; font-weight: bold;">
                        <label asp-for="mergeSortTime" style="text-align: right;">Merge Sort Time:</label>
                    </div>
                    <div class="col-1">
                        <label>@Html.DisplayFor(numbersLine => numbersLine.mergeSortTime)</label>
                    </div>
                    <div class="col-4">
                        <label>milliseconds</label>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-8 offset-8 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-50" value="Sort"/>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>
</form>

MVC_Project/sortNumbers/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sort Numbers</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="">Assignment</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="NumbersLine" asp-action="Post">Sort Numbers</a>
                    </li>
                     <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="NumbersLine" asp-action="Get">View Numbers</a>
                    </li>
                     <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="NumbersLine" asp-action="Index">Help</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Sort Numbers
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>